# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision/VisualData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class VisualData(genpy.Message):
  _md5sum = "d66a0c6279d93fd1e1e5ac20418fdde7"
  _type = "vision/VisualData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PoseStamped m1
geometry_msgs/PoseStamped m2
geometry_msgs/PoseStamped m3
geometry_msgs/PoseStamped m4
geometry_msgs/PoseStamped human_ar

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['m1','m2','m3','m4','human_ar']
  _slot_types = ['geometry_msgs/PoseStamped','geometry_msgs/PoseStamped','geometry_msgs/PoseStamped','geometry_msgs/PoseStamped','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       m1,m2,m3,m4,human_ar

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VisualData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.m1 is None:
        self.m1 = geometry_msgs.msg.PoseStamped()
      if self.m2 is None:
        self.m2 = geometry_msgs.msg.PoseStamped()
      if self.m3 is None:
        self.m3 = geometry_msgs.msg.PoseStamped()
      if self.m4 is None:
        self.m4 = geometry_msgs.msg.PoseStamped()
      if self.human_ar is None:
        self.human_ar = geometry_msgs.msg.PoseStamped()
    else:
      self.m1 = geometry_msgs.msg.PoseStamped()
      self.m2 = geometry_msgs.msg.PoseStamped()
      self.m3 = geometry_msgs.msg.PoseStamped()
      self.m4 = geometry_msgs.msg.PoseStamped()
      self.human_ar = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.m1.header.seq, _x.m1.header.stamp.secs, _x.m1.header.stamp.nsecs))
      _x = self.m1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m1.pose.position.x, _x.m1.pose.position.y, _x.m1.pose.position.z, _x.m1.pose.orientation.x, _x.m1.pose.orientation.y, _x.m1.pose.orientation.z, _x.m1.pose.orientation.w, _x.m2.header.seq, _x.m2.header.stamp.secs, _x.m2.header.stamp.nsecs))
      _x = self.m2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m2.pose.position.x, _x.m2.pose.position.y, _x.m2.pose.position.z, _x.m2.pose.orientation.x, _x.m2.pose.orientation.y, _x.m2.pose.orientation.z, _x.m2.pose.orientation.w, _x.m3.header.seq, _x.m3.header.stamp.secs, _x.m3.header.stamp.nsecs))
      _x = self.m3.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m3.pose.position.x, _x.m3.pose.position.y, _x.m3.pose.position.z, _x.m3.pose.orientation.x, _x.m3.pose.orientation.y, _x.m3.pose.orientation.z, _x.m3.pose.orientation.w, _x.m4.header.seq, _x.m4.header.stamp.secs, _x.m4.header.stamp.nsecs))
      _x = self.m4.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m4.pose.position.x, _x.m4.pose.position.y, _x.m4.pose.position.z, _x.m4.pose.orientation.x, _x.m4.pose.orientation.y, _x.m4.pose.orientation.z, _x.m4.pose.orientation.w, _x.human_ar.header.seq, _x.human_ar.header.stamp.secs, _x.human_ar.header.stamp.nsecs))
      _x = self.human_ar.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.human_ar.pose.position.x, _x.human_ar.pose.position.y, _x.human_ar.pose.position.z, _x.human_ar.pose.orientation.x, _x.human_ar.pose.orientation.y, _x.human_ar.pose.orientation.z, _x.human_ar.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.m1 is None:
        self.m1 = geometry_msgs.msg.PoseStamped()
      if self.m2 is None:
        self.m2 = geometry_msgs.msg.PoseStamped()
      if self.m3 is None:
        self.m3 = geometry_msgs.msg.PoseStamped()
      if self.m4 is None:
        self.m4 = geometry_msgs.msg.PoseStamped()
      if self.human_ar is None:
        self.human_ar = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.m1.header.seq, _x.m1.header.stamp.secs, _x.m1.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m1.pose.position.x, _x.m1.pose.position.y, _x.m1.pose.position.z, _x.m1.pose.orientation.x, _x.m1.pose.orientation.y, _x.m1.pose.orientation.z, _x.m1.pose.orientation.w, _x.m2.header.seq, _x.m2.header.stamp.secs, _x.m2.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m2.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m2.pose.position.x, _x.m2.pose.position.y, _x.m2.pose.position.z, _x.m2.pose.orientation.x, _x.m2.pose.orientation.y, _x.m2.pose.orientation.z, _x.m2.pose.orientation.w, _x.m3.header.seq, _x.m3.header.stamp.secs, _x.m3.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m3.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m3.pose.position.x, _x.m3.pose.position.y, _x.m3.pose.position.z, _x.m3.pose.orientation.x, _x.m3.pose.orientation.y, _x.m3.pose.orientation.z, _x.m3.pose.orientation.w, _x.m4.header.seq, _x.m4.header.stamp.secs, _x.m4.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m4.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m4.pose.position.x, _x.m4.pose.position.y, _x.m4.pose.position.z, _x.m4.pose.orientation.x, _x.m4.pose.orientation.y, _x.m4.pose.orientation.z, _x.m4.pose.orientation.w, _x.human_ar.header.seq, _x.human_ar.header.stamp.secs, _x.human_ar.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.human_ar.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.human_ar.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.human_ar.pose.position.x, _x.human_ar.pose.position.y, _x.human_ar.pose.position.z, _x.human_ar.pose.orientation.x, _x.human_ar.pose.orientation.y, _x.human_ar.pose.orientation.z, _x.human_ar.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.m1.header.seq, _x.m1.header.stamp.secs, _x.m1.header.stamp.nsecs))
      _x = self.m1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m1.pose.position.x, _x.m1.pose.position.y, _x.m1.pose.position.z, _x.m1.pose.orientation.x, _x.m1.pose.orientation.y, _x.m1.pose.orientation.z, _x.m1.pose.orientation.w, _x.m2.header.seq, _x.m2.header.stamp.secs, _x.m2.header.stamp.nsecs))
      _x = self.m2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m2.pose.position.x, _x.m2.pose.position.y, _x.m2.pose.position.z, _x.m2.pose.orientation.x, _x.m2.pose.orientation.y, _x.m2.pose.orientation.z, _x.m2.pose.orientation.w, _x.m3.header.seq, _x.m3.header.stamp.secs, _x.m3.header.stamp.nsecs))
      _x = self.m3.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m3.pose.position.x, _x.m3.pose.position.y, _x.m3.pose.position.z, _x.m3.pose.orientation.x, _x.m3.pose.orientation.y, _x.m3.pose.orientation.z, _x.m3.pose.orientation.w, _x.m4.header.seq, _x.m4.header.stamp.secs, _x.m4.header.stamp.nsecs))
      _x = self.m4.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.m4.pose.position.x, _x.m4.pose.position.y, _x.m4.pose.position.z, _x.m4.pose.orientation.x, _x.m4.pose.orientation.y, _x.m4.pose.orientation.z, _x.m4.pose.orientation.w, _x.human_ar.header.seq, _x.human_ar.header.stamp.secs, _x.human_ar.header.stamp.nsecs))
      _x = self.human_ar.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.human_ar.pose.position.x, _x.human_ar.pose.position.y, _x.human_ar.pose.position.z, _x.human_ar.pose.orientation.x, _x.human_ar.pose.orientation.y, _x.human_ar.pose.orientation.z, _x.human_ar.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.m1 is None:
        self.m1 = geometry_msgs.msg.PoseStamped()
      if self.m2 is None:
        self.m2 = geometry_msgs.msg.PoseStamped()
      if self.m3 is None:
        self.m3 = geometry_msgs.msg.PoseStamped()
      if self.m4 is None:
        self.m4 = geometry_msgs.msg.PoseStamped()
      if self.human_ar is None:
        self.human_ar = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.m1.header.seq, _x.m1.header.stamp.secs, _x.m1.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m1.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m1.pose.position.x, _x.m1.pose.position.y, _x.m1.pose.position.z, _x.m1.pose.orientation.x, _x.m1.pose.orientation.y, _x.m1.pose.orientation.z, _x.m1.pose.orientation.w, _x.m2.header.seq, _x.m2.header.stamp.secs, _x.m2.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m2.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m2.pose.position.x, _x.m2.pose.position.y, _x.m2.pose.position.z, _x.m2.pose.orientation.x, _x.m2.pose.orientation.y, _x.m2.pose.orientation.z, _x.m2.pose.orientation.w, _x.m3.header.seq, _x.m3.header.stamp.secs, _x.m3.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m3.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m3.pose.position.x, _x.m3.pose.position.y, _x.m3.pose.position.z, _x.m3.pose.orientation.x, _x.m3.pose.orientation.y, _x.m3.pose.orientation.z, _x.m3.pose.orientation.w, _x.m4.header.seq, _x.m4.header.stamp.secs, _x.m4.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.m4.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.m4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.m4.pose.position.x, _x.m4.pose.position.y, _x.m4.pose.position.z, _x.m4.pose.orientation.x, _x.m4.pose.orientation.y, _x.m4.pose.orientation.z, _x.m4.pose.orientation.w, _x.human_ar.header.seq, _x.human_ar.header.stamp.secs, _x.human_ar.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.human_ar.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.human_ar.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.human_ar.pose.position.x, _x.human_ar.pose.position.y, _x.human_ar.pose.position.z, _x.human_ar.pose.orientation.x, _x.human_ar.pose.orientation.y, _x.human_ar.pose.orientation.z, _x.human_ar.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
